version: "2"

services:
  master:
    image: rethinkdb:2.3.5
    command: rethinkdb --bind all --bind-http all
    ports:
      - "315:28015"
      - "29015"
      - "420:8080"
  worker:
    image: rethinkdb:2.3.5
    command: rethinkdb --join rethinkmaster --bind all
    links:
      - master:rethinkmaster